language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - LARAVEL_VERSION=5.5.*
        - TESTBENCH_VERSION=3.5.*
    - php: 7.2
      env:
        - LARAVEL_VERSION=5.6.*
        - TESTBENCH_VERSION=3.6.*
    - php: 7.2
      env:
        - LARAVEL_VERSION=5.7.*
        - TESTBENCH_VERSION=3.7.*
    - php: 7.2
      env:
        - LARAVEL_VERSION=5.8.*
        - TESTBENCH_VERSION=3.8.*
    - php: 7.2
      env:
        - LARAVEL_VERSION=6.*
        - TESTBENCH_VERSION=4.*
    - php: 7.2
      env:
        - LARAVEL_VERSION=7.*
        - TESTBENCH_VERSION=5.*
    - php: 7.3
      env:
        - LARAVEL_VERSION=5.5.*
        - TESTBENCH_VERSION=3.5.*
    - php: 7.3
      env:
        - LARAVEL_VERSION=5.6.*
        - TESTBENCH_VERSION=3.6.*
    - php: 7.3
      env:
        - LARAVEL_VERSION=5.7.*
        - TESTBENCH_VERSION=3.7.*
    - php: 7.3
      env:
        - LARAVEL_VERSION=5.8.*
        - TESTBENCH_VERSION=3.8.*
    - php: 7.3
      env:
        - LARAVEL_VERSION=6.*
        - TESTBENCH_VERSION=4.*
    - php: 7.3
      env:
        - LARAVEL_VERSION=7.*
        - TESTBENCH_VERSION=5.*
    - php: 7.4
      env:
        - LARAVEL_VERSION=5.8.*
        - TESTBENCH_VERSION=3.8.*
    - php: 7.4
      env:
        - LARAVEL_VERSION=6.*
        - TESTBENCH_VERSION=4.*
    - php: 7.4
      env:
        - LARAVEL_VERSION=7.*
        - TESTBENCH_VERSION=5.*

before_install:
  - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --prefer-dist
  - composer require "illuminate/support:${LARAVEL_VERSION}" --no-update --prefer-dist

install: travis_retry composer install --no-interaction --prefer-dist

script:
- bin/phpunit -c .
